### ISSUE TITLE
[Windows] dump_parser crashes with non-ascii characters

### ISSUE THREAD

**Issue by FRYoussef** [Grasia/wiki-scripts#1]
The script crashes and launches UnicodeEncodeError because of a contributor name like Σ, Ɱ or a name with weird characters.

Traceback (most recent call last):
  File "dump_parser.py", line 154, in module
    if xml_to_csv(xmlfile):
  File "dump_parser.py", line 140, in xml_to_csv
    parser.ParseFile(input_file)
  File "..\Modules\pyexpat.c", line 468, in EndElement
  File "dump_parser.py", line 106, in end_tag
    output_csv.write(";".join(revision_row) + '\n')
  File "...\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u03a3' in position 60: character maps to undefined

**Comment by Akronix** [comment]
After some research (see [this](https://stackoverflow.com/questions/14630288/unicodeencodeerror-charmap-codec-cant-encode-character-maps-to-undefined#16120218), and [this](https://stackoverflow.com/questions/25127673/how-to-print-utf-8-to-console-with-python-3-4-windows-8), and [this](https://stackoverflow.com/questions/30539882/whats-the-deal-with-python-3-4-unicode-different-languages-and-windows/30551552#30551552).); I think this is due to your Windows terminal, and, actually, not to the python code.

Might you try to set the envvar PYTHONIOENCODING to utf-8 (`set PYTHONIOENCODING=utf8`) and run the script again?

Also, can you give the output of running this Python code?:
```
import sys
sys.stdout.encoding
```

**Comment by FRYoussef** [comment]
Thanks,
The Windows console shows UTF-8 with that Python code, but never mind, I ran it on Linux console and worked fine !!

**Comment by FRYoussef** [comment]
Even with the env var the script crashes on Windows.
I must say, I use python3.

Thank you.

**Comment by Akronix** [comment]
:confused: Still, It looks to me to a misconfiguration in the Windows environment, terminal or Python environment since Python 3 uses utf-8 by default and those characters should be fine as they are in the input file or in Linux.
I don't use windows, so I expect someone else who does to take a deeper look at this and try to find the solution.

**Comment by FRYoussef** [comment]
Finally I´ve found it!!
The error was on the encode file not in the output.
If you change the line 134 to: **output_csv = open(filename[0:-3]+"csv",'w', encoding='utf8')**
you´ll solve it.

Regards.

**Comment by Akronix** [comment]
May you `git pull` the latest changes in master branch and check if it's working?

**Comment by Akronix** [comment]
Tested in GNU/Linux and it works correctly

**Comment by FRYoussef** [comment]
I've tested it on Windows 10 / Debian and it works properly (Python 3)
Should it work with Python 2? because mine not on Debian

**Comment by Akronix** [comment]
No, all the scripts are python3 only actually, both python2 and python3 are incompatible).
You did it just fine. Thank youi
